### ISSUE TITLE
Show Logs doesn't open any terminal view 

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-tekton#103]
If you click on show logs the terminal view doesn't show up and the tab with logs requested is not opened.

**Comment by jeffmaury** [comment]
First analysis: this is cause by 2018.3 OpenShift Connector on 2018.2 is ok same issue on 2018.3
Workaround is to previously open the Terminal window

**Comment by jeffmaury** [comment]
Test results:
Version|Result
--------|-------
2018.3|KO
2019.1|OK
2019.2|OK
2019.3|OK
2020.1|OK

**Comment by jeffmaury** [comment]
See https://github.com/redhat-developer/intellij-common/pull/8

**Comment by jeffmaury** [comment]
@lstocchi ok to close ?

**Comment by lstocchi** [comment]
Yes, just tested. It works.
