### ISSUE TITLE
Claim new release requires v1Beta1 and Triggers

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-tekton#118]
Opening this as a reminder when we are going to release the new version of the plugin. 

Now it works with beta1 and triggers. We should clearly explain to users they require beta1 otherwise the plugin won't work correctly and they will need to install triggers to enable them in the plugin.

**Comment by jeffmaury** [comment]
Fixed by 5946367c9fdc7a4dfaf609744c01c041b327a84f
