### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/intellij-tekton#12]
We should add integration tests so that we can validate that changing the CLI version does not impact the experience.
We could follow what has been done for the IntelliJ OpenShift Connector (https://github.com/redhat-developer/intellij-openshift-connector) with the fact that we need to check on upstream Kubernetes and also on OpenShift. For Kubernetes, we can use Kind (https://kind.sigs.k8s.io/docs/user/quick-start/) as Travis provides a Docker env by default.

**Comment by lstocchi** [comment]
Closing this as it's old. We already have integration tests and they are integrated with new ones when we update the cli
