### ISSUE TITLE
Tekton catalog integration

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/intellij-tekton#121]
Tekton catalog provides a catalog of reusable tasks and pipelines. It would be good to integration it when user creates a pipelines.

**Comment by evidolob** [comment]
Corresponding issue for `vscode-tekton`: https://github.com/redhat-developer/vscode-tekton/issues/187

**Comment by lstocchi** [comment]
@siamaksade I wanted to start working on this but, first, i wanted to hear from you as i saw there is a `blocked` tag on the corresponding issue in vscode.

My idea was this. I wanted to create a script to download all tasks from https://github.com/tektoncd/catalog and use them as snippets in the plugin. So everytime we release a new version, the script is launched and the plugin goes to the marketplace with the catalog updated to the current date.

Right now there is only one snippet for task, one for pipeline and so on... which are basically skeletons so users can start working on a base and edit them without starting from scratch. My idea would be to have a similar workflow. Users can pick a task or pipeline from a list of all resources downloaded from the catalog (we could add a button in the context menù `open from catalog`, which will show up a list of tasks available), edit it and save in the cluster to be reused later. 
WDYT? Why is there the `blocked` tag? Thank you.
