### ISSUE TITLE
Running time wongly computed

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/intellij-tekton#205]
A pipeline running is displayed with wrong running time: we need to protected it.

![image](https://user-images.githubusercontent.com/695993/92746340-7fe1ef00-f383-11ea-8488-c8f2faf3047d.png)

**Comment by lstocchi** [comment]
i'm not able to replicate it :/ @jeffmaury you or your cluster live in the future lol
This is clearly an issue with different timing from the cluster and the local machine. How do you think it should be handled?

**Comment by jeffmaury** [comment]
Negative values should be rounded to 0

**Comment by lstocchi** [comment]
@jeffmaury This should be fixed by https://github.com/redhat-developer/intellij-common/pull/15 . Can you please verify whenever you have time? I'm not able to replicate it. Thank you
