### ISSUE TITLE
Add code completion for when clause

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/intellij-tekton#209]
Pipeline added a new field `when` for simpler conditional execution of tasks. (See https://github.com/tektoncd/pipeline/pull/3135)
We may provide some code completion, note sure because the doc mentions that both Input and Values are static.

**Comment by jerop** [comment]
@jeffmaury to clarify, the inputs or values can be static or variables (parameter or task results variables are supported now)

**Comment by lstocchi** [comment]
Thanks for the clarification @jerop
