### ISSUE TITLE
Update schema for when expression using task

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-tekton#220]
A when expression can be created by using the triple (Input/Operator/Value) or by defining a task that produces a skip result.
Schema validation works fine with the first option but it doesn't recognize the second.

![image](https://user-images.githubusercontent.com/49404737/93586005-f7c5a000-f9a7-11ea-94e1-4ae464526a6b.png)

Info at https://github.com/tektoncd/community/blob/master/teps/0007-conditions-beta.md#tasks-that-produce-skip-result

**Comment by jeffmaury** [comment]
According to 0.16.0; here is the definition of WhenExpression:

```
type WhenExpression struct {
	// Input is the string for guard checking which can be a static input or an output from a parent Task
	Input string
	// Operator that represents an Input's relationship to the values
	Operator selection.Operator
	// Values is an array of strings, which is compared against the input, for guard checking
	// It must be non-empty
	Values []string
}

Will check if 0.16.x update this definition
```

**Comment by jeffmaury** [comment]
Can find this definition in following 0.16.x release so going to ask to the Tekton dev ML

**Comment by jeffmaury** [comment]
Discussion link: https://groups.google.com/g/tekton-dev/c/ZrIo8hSdcf4

**Comment by jeffmaury** [comment]
@lstocchi ok to close ?

**Comment by lstocchi** [comment]
Yes :+1:
