### ISSUE TITLE
Handle optional workspaces

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/intellij-tekton#241]
Tekton Pipelines 0.17.0 introduces the notion of optional workspaces. That will probably impact our start wizard

See #240

**Comment by lstocchi** [comment]
Stuck for the moment. Opened an issue https://github.com/tektoncd/cli/issues/1290

**Comment by lstocchi** [comment]
Should be fixed https://github.com/tektoncd/cli/pull/1377

**Comment by lstocchi** [comment]
https://github.com/tektoncd/cli/pull/1465 has been merged.
