### ISSUE TITLE
Add preferences for the plugin

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/intellij-tekton#247]
I think we should improve the user experience by adding preferences for the plugin.
Here is my initial contribution
- default behavior when deleting resources (related resources) so that user does not have to select the checkbox (default false)
- always show start wizard: in the case of a task/pipeline without required input, we still show the wizard in order to configure authentication information. We could relax that. Default true

**Comment by lstocchi** [comment]
Another thing that can be related to this is the `config-defaults` ConfigMap inside the tekton-pipelines namespace. You can use it to specify information about defaults, such as timeouts, service accounts, etc. for PipelineRuns/TaskRuns. 
We could also show some of this preferences in the plugin and use the k8s ext to create/update the configMap.
