### ISSUE TITLE
Improve colours in graph for dark schema

### ISSUE THREAD

**Issue by jkopriva** [redhat-developer/intellij-tekton#271]
The colours for dark schema in graph of pipeline are quite unreadable:
![image](https://user-images.githubusercontent.com/17871936/98348769-75597400-2019-11eb-9eb4-0b4138c41b46.png)

Also the text are not in rectangles.

**Comment by jkopriva** [comment]
Another screenshot: 
![image](https://user-images.githubusercontent.com/17871936/98349009-c2d5e100-2019-11eb-8822-5594cba3c17f.png)

**Comment by jeffmaury** [comment]
Duplicates #238
