### ISSUE TITLE
Show Diagnostics button on template does nothing

### ISSUE THREAD

**Issue by jkopriva** [redhat-developer/intellij-tekton#272]
(I have followed this turorial for creating pipeline: https://github.com/openshift/pipelines-tutorial#deploy-sample-application)

When I right click on Pipeline Run and select Show Diagnostics Data from context menu it does nothing, not even some info dialog is shown.

**Comment by lstocchi** [comment]
Closing it as i'm not able to replicate it. I also tried closing the terminal view or focussing on another tab, but the new terminal tab created is focussed correctly and i can see the actual output. Feel free to reopen it if you see it again. Thanks!!
