### ISSUE TITLE
Display active namespace in tree view.

### ISSUE THREAD

**Issue by sudhirverma** [redhat-developer/intellij-tekton#280]
It would be good to display the active namespace in the tree view to have similar behavior as in vscode-tekton. Rather than displaying all namespace in the tree view.

**Comment by lstocchi** [comment]
+1. This is something we already thought about. The problem we have is that we don't have any k8s plugin to rely on to allow users to switch namespace/project from the ide itself. As soon as andre's k8s plugin will be ready we can use that one to accomplish this.
