### ISSUE TITLE
Report ordering used in finally tasks

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/intellij-tekton#285]
As per the documentation, finally tasks are simply executed concurrently and ordering is not supported.
So if runAfter is used in a finally task it should be reported as a warning message

**Comment by lstocchi** [comment]
How do you expect this should work?
The user still has an error message in the notification if he tries to save the pipeline.
```
 validation failed: invalid value: no runAfter allowed under spec.finally, final task secondo has runAfter specified: spec.finally
```

**Comment by jeffmaury** [comment]
So I think we should report as error then.
