### ISSUE TITLE
Error in tekton trigger schema validation when Kubernetes extension is installed

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-tekton#287]
Users see errors if using the triggers resources when the kubernetes extension is installed.

![image](https://user-images.githubusercontent.com/49404737/100857631-34744400-348d-11eb-9af0-f194ba7de8a2.png)

**Comment by jeffmaury** [comment]
The payload is invalid: the apiVersion is missing the version part.
See https://github.com/tektoncd/cli/issues/1230

**Comment by lstocchi** [comment]
@jeffmaury Tried with the new cli and even with the version i still face the problem. I think the kubernetes extension is not smart enough to recognize the triggers apiVersion.

![image](https://user-images.githubusercontent.com/49404737/100863850-75705680-3495-11eb-8872-00acce14df1c.png)
