### ISSUE TITLE
Remove clutter from Yaml configurations

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-tekton#309]
I came across this plugin that removes all useless things from a yaml output so to make the resource more readable https://github.com/itaysk/kubectl-neat and i was thinking if we should do something similar here. 

Like adding an option so the user can tell the plugin "when downloading and showing resources in the IDE editor, remove all stuff considered redundant as i don't care about them and make everything more readable". WDYT? @jeffmaury 

cc @adietish something that could work for the k8s plugin as well

**Comment by lstocchi** [comment]
Adding it here for reference https://github.com/tektoncd/cli/issues/1220

**Comment by adietish** [comment]
@lstocchi just discovered notifications in github ;). Awesome idea, like it! filed https://github.com/redhat-developer/intellij-kubernetes/issues/274
