### ISSUE TITLE
Parameter with default is requested

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/intellij-tekton#313]
The **curl** task from the Tekton Hub has an **options** parameter which has a default value.
However, when if want to start this task, the wizard wants me to fill a value

**Comment by lstocchi** [comment]
We should already have this feature. I tried and it works fine for me. Doesn't it work with any pipeline/task or it is just the curl task from the hub? 

![default_value](https://user-images.githubusercontent.com/49404737/103874885-001a2600-50d2-11eb-9ed8-d339277d320a.gif)

**Comment by jeffmaury** [comment]
Can you enter an URL and click the Next button ?

**Comment by lstocchi** [comment]
Ah ok, i see what you mean, yeah it's not working.

**Comment by jeffmaury** [comment]
Still can't start the task without entering some values in the options fields
