### ISSUE TITLE
Should use telemetry

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-tekton#331]
In https://github.com/adietish/intellij-redhat-telemetry a telemetry plugin is being developed. We should use it in intellij-tekton.

**Comment by lstocchi** [comment]
Are we adding telemetry to IJ Tekton now? Don't we need to have an "OK" from some PMs? From what i understood in last cabal, Fred said only few plugins were allowed to use telemetry at the beginning for testing, no? Is IJ Tekton one of those?

@jeffmaury Do you already have in mind which things/actions do we need to catch/log?

**Comment by jeffmaury** [comment]
No this is OK now. I would start recording actions first

**Comment by lstocchi** [comment]
@jeffmaury i thought about it when you were talking about recording IJ versions. It could be useful for us to check how many ppl uses this plugin on tekton with triggers enabled and which versions of them they are using (the same with tekton pipelines version) ... as there were breaking changes in past, so we know what to do and how urgent it is (e.g https://github.com/redhat-developer/intellij-tekton/issues/252)

**Comment by lstocchi** [comment]
Closing it as https://github.com/redhat-developer/intellij-tekton/pull/341 was merged. Thanks @adietish :rocket:
