### ISSUE TITLE
Should improve dialog to confirm "Delete Resource"

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-tekton#332]
When you delete resources you have to confirm that you really want to delete those by confirming the following dialog:
![image](https://user-images.githubusercontent.com/25126/106772836-b117d000-6640-11eb-9e4a-13663418f832.png)

* The text for the checkbox **"Yes, delete the clustertask..."** is lengthy, repeats what's already said above and is not very clear: I didn't fully understand right away that it only concerns the related resources. 
Taking advice from the jetbrains style guide (which suggests using short and clear text at https://jetbrains.design/intellij/text/writing_short/) I'd maybe write just **Delete related resources**
* Same is true for **"The clustertask may also have..."**. 
I think that we can shorten it to **"Clustertask have related resources (ex. clustertaskRuns)"** or even drop it completely by adding the info to the checkbox label **"Delete resources related to clustertask [name]"**
* Same is true for **"Are you sure you want to delete...?"**. Jetbrains style guide says: "Remove verbs that explain the function of a UI control", "Do not address the user"
I would shorten it to **"Delete clustertask [name]?"**

**Comment by lstocchi** [comment]
Even Jetbrains doesn't follow its own rules :smile: 
![image](https://user-images.githubusercontent.com/49404737/109951833-74420600-7cde-11eb-85c4-c255a43095ea.png)
