### ISSUE TITLE
Cannot save template unchanged and have it pushed to cluster

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-tekton#333]
As a dummy user I'd expect that I can push the suggested "template" (that I have in my editor) without further changes. It's not apparent to me that I have to change something so that I can push it. 
We should imho either inform the user or allow the editor to be pushed as is. 

**Steps:**
1. EXEC: Select resource type in Tekton tree (ex. ClusterTasks)
2. EXEC: Pick "New <resource type>" item in context menu
3. ASSERT: editor with a template is opened
4. EXEC: hit Ctrl + S

**Result:**
Nothing happens

**Expected result:**
I am asked if I want to push the editor content as-is to the cluster

**Required steps so that template can be pushed:**
6. EXEC: in editor: change metada > name
7. EXEC: hit Ctrl + S
8. ASSERT: Dialog "Save to Cluster > Do you want to push the changes to the cluster?" appears
9. EXEC: hit "Yes"
10. ASSERT: new resource is pushed and appears in the tree

**Comment by lstocchi** [comment]
Closing it as we now rely on the push/pull by IJ Kubernetes plugin which handles this perfectly
