### ISSUE TITLE
master doesn't compile

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-tekton#342]
```gradle clean buildPlugin``` produces the following compilation error:
```
/Users/andredietisheim/Documents/jboss-workspaces/intellij-tekton/src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java:492: error: cannot find symbol
            ExecHelper.executeWithUI(envVars, outputToEditor(fileName),command, "pipelinerun", "logs", pipelineRun, "-f", "-n", namespace);
                      ^
  symbol:   method executeWithUI(Map<String,String>,Consumer<String>,String,String,String,String,String,String,String)
  location: class ExecHelper
```

**Comment by jeffmaury** [comment]
Which version of intellij-common are you using

**Comment by adietish** [comment]
@jeffmaury tekton is using 0.0.1-SNAPSHOT even though it's using API that's present in 0.0.2 only

**Comment by adietish** [comment]
@jeffmaury so you're saying that the last 0.0.1-SNAPSHOT before (final) 0.0.1 had the change? Maybe this was then caused by my local cache having an outdated 0.0.1-SNAPHSOT (without the change)?
