### ISSUE TITLE
Should not be interrupted by "Save to cluster" dialog when editing resource name 

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-tekton#346]
When - in a freshly started IDE - I create a new resource and edit the name in the template I get interrupted by the dialog to save the resource to the cluster. I am not able to fully set the name, the resource is saved with an incomplete name if I choose to save it. It will even error if I edit something else than the name and a resource with the name suggested by the template already exists.

**Steps:**
1. ASSERT: have a freshly started IDE
2. EXEC: in Tekton tree: select "CluterTasks" and pick "New ClusterTask"
3. ASSERT: editor with ClusterTask templated is opened
4. EXEC: put the cursor behind "foo" that's currently the value for the name of the resource and start typing: quickly hit "123"
5. ASSERT: initially only "1" appears but then disappears and you're interrupted by a dialog "Non-Project Files Protection" that asks you if you want to edit the file
![image](https://user-images.githubusercontent.com/25126/107775887-2ff7c180-6d41-11eb-84e3-cae8b1b2c234.png)
6. EXEC: choose an option that allows you to edit and confirm with "OK"
7. ASSERT: you see "1" appear again but "23" don't. 
7. ASSERT: you're interrupted by another dialog, "Save to cluster"
![image](https://user-images.githubusercontent.com/25126/107776036-5e759c80-6d41-11eb-9eed-4e92843d8dce.png)
8. EXEC: Confirm the dialog with "OK"
9. ASSERT: the resource "foo1" is saved to the cluster and appears in the tree
10. EXEC: complete the name to "foo123" and hit save
11. EXEC: Confirm the "Save to cluster" dialog that appears
12. ASSERT: another resource is created and appears in the tree

I believe that this is unexpected in several ways:
* I didn't save the file when I was first asked to save it to the cluster
* I had a resource created that was missing "23" in it's name. I wasn't aware if I didn't closely watch what happened in the editor ("23" had not been added to the name). The dialog didnt tell me about this mistake, it didn't tell me what resource it was saving (see #347)
* The "Save to cluster" dialog is modal, so I have no chance to verify the contents of the editor before I confirm it (see #348)

**Comment by lstocchi** [comment]
This can be closed as many things have changed in latest releases and it has been fixed. Non-project files protection dialog doesn't show up anymore, the dialog to save the resource displays the name of the resource to prevent wrong savings.
