### ISSUE TITLE
Update CRC download url on jetbrains plugin page

### ISSUE THREAD

**Issue by valaparthvi** [redhat-developer/intellij-tekton#349]
/type documentation
/type bug

> To run the instance of an OpenShift cluster locally, developers can use CRC / CDK / minishift.

The URL for CRC download in plugin overview points to https://developers.redhat.com/products/crc/download/ which returns a 404.

Reference - https://plugins.jetbrains.com/plugin/14096-tekton-pipelines-by-red-hat

**Comment by jeffmaury** [comment]
Seems https://developers.redhat.com/products/openshift/download is the one to use now
