### ISSUE TITLE
Cannot edit and save existing ClusterTask

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-tekton#355]
**Steps:**
1. EXEC: pick "New Cluster Task" in context menu "ClusterTasks" in toolwindow tree 
2. ASSERT: editor with ClusterTask template shows up
3. EXEC: change **metadata > name** (ex. change "foo" to "foo3")
4. EXEC: save the editor and answer "Yes" when asked (by a dialog) if you want to "Save to Cluster"
5. ASSERT: new ClusterTask shows up in the tree
6. EXEC: select the new ClusterTask and pick "Open in Editor" in the context for this resource in the tree
7. ASSERT: editor with the resource shows up
8. EXEC: change **spec > steps > script** and save the editor (ex. change 'echo \"Hello\"' to 'echo \"Hello World\"')
9. EXEC: when asked if you want to "Save to Cluster" hit "Yes".

**Result:**
Saving to the cluster errors complaining about the property **resourceVersion**:
```
21:16	Error
			An error occurred while saving 
			An error occurred while saving ClusterTask foo3
			resourceVersion should not be set on objects to be created
			Failure executing: POST at: https://api.crc.testing:6443/apis/tekton.dev/v1beta1/clustertasks. Message: resourceVersion should not be set on objects to be created. Received status: Status(apiVersion=v1, code=500, details=null, kind=Status, message=resourceVersion should not be set on objects to be created, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=null, status=Failure, additionalProperties={}).
```

10. EXEC: in the editor: remove **metadata > resourceVersion** and save the editor & confirm "Save to Cluster"

**Result:**
  Saving to cluster fails complaining that the resource already exists
```
21:19	Error
			An error occurred while saving 
			An error occurred while saving ClusterTask foo3
			clustertasks.tekton.dev "foo3" already exists
			Failure executing: POST at: https://api.crc.testing:6443/apis/tekton.dev/v1beta1/clustertasks. Message: clustertasks.tekton.dev "foo3" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=tekton.dev, kind=clustertasks, name=foo3, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=clustertasks.tekton.dev "foo3" already exists, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}).
```

**Comment by lstocchi** [comment]
@adietish i tried to replicate it without any success. Could you please verify it and tell me if you still face it? Maybe it was fixed somehow. Thanks!

**Comment by adietish** [comment]
@lstocchi can't replicate this any more. Looks like this was fixed. Awesomeness!
