### ISSUE TITLE
Not intuitive that "combo" triggers action when clicked in the white area

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-tekton#358]
**Steps:**
1. EXEC: in tool window tree: select "Tasks" category and open ctx menu
2. EXEC: pick "Import from Tekton Hub"
3. ASSERT: dialog with all available tasks in Tekton hub opens up and lists all available tasks (that one may install to the cluster)
4. ASSERT: next to an item there's a button labeled "install" that looks like a combo.
![image](https://user-images.githubusercontent.com/25126/108755792-f9435780-7547-11eb-9fbf-439d88c4756d.png)
5. EXEC: click the button (in the white area, not on the 2 arrows on the right)

**Result:**
The "combobox"-button would install, one can notice as clicking in results in a dialog appearing that asks if the task should be saved to the cluster.

**Expected result:**
The "combobox"-button should not look like a combo that one can click and discover more options. Clicking it results in installing the task to the cluster, not opening up a list of options.

**Comment by jeffmaury** [comment]
That's on purpose because you can also install the task as cluster task

**Comment by adietish** [comment]
> That's on purpose because you can also install the task as cluster task

Can you explain please? My point is that intuitively a user would expect a combo to show a list of options. Here, the button isn't a combo, it's a button that triggers an action. It thus think that it should look like a button.

**Comment by adietish** [comment]
Ah, I grocked it, when clicking on the 2 arrows, it really is a combo:
![image](https://user-images.githubusercontent.com/25126/108766940-0bc48d80-7556-11eb-9ac3-4bfd92ecac72.png)
But when clicked on the white are it'll install directly. This wasn't obvious to me. I'll thus reformulate in the sense that it isn't obvious when the button acts like a combo and when as a button. 
In MacOS combos (that I ack look similar to this combo) list items when clicked anywhere, not just when clicked on the arrows on the right. It is thus confusing to MacOS users which dont expect this behaviour. Btw. the version combo in the details pane on the right behaves in this way. It'll list the options whereever you click.
I'd thus either change the behaviour (list the options regardless where one clicks - and then add a separate, explicit "Install" button in the details pane) or at least explain this somewhere in the dialog.

**Comment by adietish** [comment]
Furthermore it isn't clear as what it would install when the 2nd option "Install" is selected:
![image](https://user-images.githubusercontent.com/25126/108768663-39aad180-7558-11eb-88bb-a896a72d59a9.png)
What does it do in this 2nd option?

**Comment by jeffmaury** [comment]
No need. You are working on a task, so install it in the cluster.

**Comment by adietish** [comment]
> No need. You are working on a task, so install it in the cluster.

I'm sorry, but I dont understand what this exactly means? If not installed as ClusterTask, as what is it installed? How would a dummy user know?

**Comment by jeffmaury** [comment]
My guess because user is working on an item from Hub ie a task so install should be enough

**Comment by adietish** [comment]
In #423 labels are much more clear. The main button but also the alternative that one gets when he hits the arrow both state what they would install:
![image](https://user-images.githubusercontent.com/25126/121328697-d5e4c280-c914-11eb-9cd0-c16d8e392deb.png)
Nice improvement to me!
