### ISSUE TITLE
Can "Add Trigger" to all resource categories but it does nothing

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-tekton#360]
**Steps:**
1. EXEC: select ClusterTask (or any other) category and open the ctx menu
2. ASSERT: ctx menu contains an item "Add Trigger"
![image](https://user-images.githubusercontent.com/25126/108765053-a2437f80-7553-11eb-9b2b-a23491036acb.png)
3. EXEC: click on "Add Trigger"

**Result:**
Nothing happens.

**Comment by lstocchi** [comment]
it should be fixed when https://github.com/redhat-developer/intellij-tekton/pull/352/files is merged
