### ISSUE TITLE
Add Trigger wizard should have "Cancel" button, only has "Next" & "Previous"

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-tekton#365]
**Steps:**
1. ASSERT: have tekton triggers installed in your cluster
2. ASSERT: have a valid pipeline, ex.
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: "2021-02-24T14:20:24Z"
  generation: 1
  managedFields:
  - apiVersion: tekton.dev/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:params: {}
        f:tasks: {}
    manager: okhttp
    operation: Update
    time: "2021-02-24T14:20:23Z"
  name: pipeline-with-params
  namespace: default
  resourceVersion: "1067229"
  selfLink: /apis/tekton.dev/v1beta1/namespaces/default/pipelines/pipeline-with-params
  uid: 19ca63f7-5e99-40f3-9c54-1b8c8ffb82f7
spec:
  params:
  - default: "1"
    name: pl-param-x
    type: string
  - default: "1"
    name: pl-param-y
    type: string
  tasks:
  - name: sum-params
    params:
    - name: a
      value: $(params.pl-param-x)
    - name: b
      value: $(params.pl-param-y)
    taskRef:
      kind: Task
      name: sum-params
  - name: multiply-params
    params:
    - name: a
      value: $(params.pl-param-x)
    - name: b
      value: $(params.pl-param-y)
    taskRef:
      kind: Task
      name: multiply-params
```
3. EXEC: select your pipeline in tree and pick "Add Trigger" in the ctx menu
4. ASSERT: the "Add Trigger" wizard shows up.
![image](https://user-images.githubusercontent.com/25126/109028026-aee5e600-76c1-11eb-9526-e652217c0878.png)
5. EXEC: try to cancel it

**Result:**
You're looking for a "Cancel" button in the button bar, next to "Next" and "Previous" but it's missing. You can only cancle the wizard via the close button in the title bar (left on MacOS, right on other OS'es)

**Expected result:**
There should be a cancel button close to "Next" and "Previous" as it is usual in the wizards.

**Comment by lstocchi** [comment]
In other OSes we already have the cancel button so i guess it is only related to Mac
![image](https://user-images.githubusercontent.com/49404737/109925826-857d1980-7cc2-11eb-9a58-29c41c67b561.png)
