### ISSUE TITLE
Code completion for inline tasks

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-tekton#368]
Add code completion snippet for inline tasks in a Pipeline under tasks

**Comment by lstocchi** [comment]
After looking at what vscode offers i guess we can close it. We already have a code completion/validation which is quite cool. I don't think that an empty snippet will add this great value. 
![image](https://user-images.githubusercontent.com/49404737/117342685-cac8ed80-aea3-11eb-87f6-bc53ec1290c9.png)

WDYT @jeffmaury ? Vscode demo at https://github.com/redhat-developer/vscode-tekton/pull/550

**Comment by jeffmaury** [comment]
I agree with you but I'm wondering why @siamaksade opened it on the VSCode side as I think where you are under the `tasks` node, the code completion is pretty much similar between IJ ans VSCode

**Comment by lstocchi** [comment]
Now the man to ping is @mohitsuman

**Comment by mohitsuman** [comment]
As discussed, there is already code completion workflow for tasks.
