### ISSUE TITLE
Should be able to switch current namespace

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-tekton#382]
The current impl only shows the current namespace and it's resources. There's currently no way to switch the current namespace in the IDE so that one can look into the resources of other namespaces. 

![image](https://user-images.githubusercontent.com/25126/110766667-b4146a80-8255-11eb-8bb3-e4d5724ab035.png)

The only way to achieve this currently is to change the current namespace via kubectl/oc.

**Comment by lstocchi** [comment]
This is related to #370
