### ISSUE TITLE
Add telemetry information for cluster connected to

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/intellij-tekton#416]
### Goal
Provide the cluster version information the user connects to through the extension

### Acceptance Criteria
- The extension should send data to telemetry, regarding the connected cluster version.
- This should cover OpenShift and Kubernetes clusters

**Comment by jeffmaury** [comment]
Not sure to get why Tekton upstream tooling is dealing with OpenShift related stuff

**Comment by mohitsuman** [comment]
Ideally this should be any cluster connected to, be it Kubernetes or OpenShift.

**Comment by jeffmaury** [comment]
So, if it is a Kubernetes cluster, do you want the Kubernetes version and if it is an OpenShift one the OpenShift version. Please note that there is no way to get the OpenShift version on OCP4 without admin rights

**Comment by mohitsuman** [comment]
yes, currently we are not able to get the OpenShift version for non-admin users, I will try to sync up with `oc` team to see if we have any solution for it. But meanwhile for admin users, we can use the information.

**Comment by jeffmaury** [comment]
The following information will be recorded:

- Kubernetes version
- flag for OpenShift/Kubernetes cluster type
- OpenShift version (may be absent on OCP4 and non admin access)

A utility will be provided in IntelliJ common to retrieve these infos as IJ Tekton and IJ Knative may also require it

**Comment by jeffmaury** [comment]
See https://github.com/redhat-developer/intellij-common/issues/76
